apiVersion: v1
kind: Service

metadata:
  name: bgg-app-svc
  namespace: workshop-day2

spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: bgg-app-pod
  ports:
  - name: bgg-app-port
    port: 80
    targetPort: bgg-app-port

