apiVersion: v1
kind: Service

metadata:
  name: bgg-db-svc
  namespace: workshop-day2

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bgg-db-pod
  ports:
  - name: bgg-service-port
    port: 3306
    targetPort: bgg-db-port
