apiVersion: v1
kind: PersistentVolumeClaim

# kubectl get sc
metadata:
  name: bggdbpvc
  namespace: workshop-day2
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "dobs.csi.digitalocean.com"

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
